version: '3'

services:
  file:
    image: java:8u111-jre-alpine
    container_name: file
    ports:
     - "7020:8080"
    volumes:
     - ./opt:/opt/
     - ./archive:/archive/
    entrypoint: java -jar /opt/rest-document-archive-0.1.0.jar
    labels:
        - traefik.frontend.rule=Host:file.services.alin.be
        - traefik.backend=file
        - traefik.frontend.entryPoints=http,https
        - traefik.port=8080
    networks:
        - web

networks:
  web:
    external:
      name: traefik_webgateway
