version: '3.5'

services:
  file:
    image: msfile-image
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 100M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=8080
        - traefik.frontend.rule=Host:file.services.alin.be
        - traefik.frontend.entryPoints=http,https
        - traefik.backend.loadbalancer.method=wrr
    volumes:
     - ./archive:/archive/
    entrypoint: java -jar /opt/rest-document-archive-0.1.0.jar

networks:
  default:
    external:
      name: traefik-net
